// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/protobuf/schema/fleet.proto

package fleet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vehicle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FleetNumber       string `protobuf:"bytes,1,opt,name=fleet_number,json=fleetNumber,proto3" json:"fleet_number,omitempty"`
	OperationalStatus string `protobuf:"bytes,2,opt,name=operational_status,json=operationalStatus,proto3" json:"operational_status,omitempty"`
	Lfb               string `protobuf:"bytes,3,opt,name=lfb,proto3" json:"lfb,omitempty"`
	Make              string `protobuf:"bytes,4,opt,name=make,proto3" json:"make,omitempty"`
	Model             string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Type              string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Category          string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	RegistrationYear  int32  `protobuf:"varint,8,opt,name=registration_year,json=registrationYear,proto3" json:"registration_year,omitempty"`
	Life              int32  `protobuf:"varint,9,opt,name=life,proto3" json:"life,omitempty"`
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetFleetNumber() string {
	if x != nil {
		return x.FleetNumber
	}
	return ""
}

func (x *Vehicle) GetOperationalStatus() string {
	if x != nil {
		return x.OperationalStatus
	}
	return ""
}

func (x *Vehicle) GetLfb() string {
	if x != nil {
		return x.Lfb
	}
	return ""
}

func (x *Vehicle) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Vehicle) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Vehicle) GetRegistrationYear() int32 {
	if x != nil {
		return x.RegistrationYear
	}
	return 0
}

func (x *Vehicle) GetLife() int32 {
	if x != nil {
		return x.Life
	}
	return 0
}

type VehicleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationalStatus string `protobuf:"bytes,2,opt,name=operational_status,json=operationalStatus,proto3" json:"operational_status,omitempty"`
	Lfb               string `protobuf:"bytes,3,opt,name=lfb,proto3" json:"lfb,omitempty"`
	Make              string `protobuf:"bytes,4,opt,name=make,proto3" json:"make,omitempty"`
	Model             string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Type              string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Category          string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	RegistrationYear  int32  `protobuf:"varint,8,opt,name=registration_year,json=registrationYear,proto3" json:"registration_year,omitempty"`
	Life              int32  `protobuf:"varint,9,opt,name=life,proto3" json:"life,omitempty"`
}

func (x *VehicleRequest) Reset() {
	*x = VehicleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleRequest) ProtoMessage() {}

func (x *VehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleRequest.ProtoReflect.Descriptor instead.
func (*VehicleRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleRequest) GetOperationalStatus() string {
	if x != nil {
		return x.OperationalStatus
	}
	return ""
}

func (x *VehicleRequest) GetLfb() string {
	if x != nil {
		return x.Lfb
	}
	return ""
}

func (x *VehicleRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VehicleRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VehicleRequest) GetRegistrationYear() int32 {
	if x != nil {
		return x.RegistrationYear
	}
	return 0
}

func (x *VehicleRequest) GetLife() int32 {
	if x != nil {
		return x.Life
	}
	return 0
}

type GetVehiclesByOpStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetVehiclesByOpStatusRequest) Reset() {
	*x = GetVehiclesByOpStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVehiclesByOpStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehiclesByOpStatusRequest) ProtoMessage() {}

func (x *GetVehiclesByOpStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehiclesByOpStatusRequest.ProtoReflect.Descriptor instead.
func (*GetVehiclesByOpStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *GetVehiclesByOpStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetVehiclesByYearRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year int32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *GetVehiclesByYearRequest) Reset() {
	*x = GetVehiclesByYearRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVehiclesByYearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehiclesByYearRequest) ProtoMessage() {}

func (x *GetVehiclesByYearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehiclesByYearRequest.ProtoReflect.Descriptor instead.
func (*GetVehiclesByYearRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *GetVehiclesByYearRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type GetFleetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year *int32  `protobuf:"varint,1,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Make *string `protobuf:"bytes,2,opt,name=make,proto3,oneof" json:"make,omitempty"`
}

func (x *GetFleetStatsRequest) Reset() {
	*x = GetFleetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFleetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetStatsRequest) ProtoMessage() {}

func (x *GetFleetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetFleetStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *GetFleetStatsRequest) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *GetFleetStatsRequest) GetMake() string {
	if x != nil && x.Make != nil {
		return *x.Make
	}
	return ""
}

type GetFleetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active     int32   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Reserve    int32   `protobuf:"varint,2,opt,name=reserve,proto3" json:"reserve,omitempty"`
	Training   int32   `protobuf:"varint,3,opt,name=training,proto3" json:"training,omitempty"`
	AverageAge float32 `protobuf:"fixed32,4,opt,name=average_age,json=averageAge,proto3" json:"average_age,omitempty"`
}

func (x *GetFleetStatsResponse) Reset() {
	*x = GetFleetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFleetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetStatsResponse) ProtoMessage() {}

func (x *GetFleetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetFleetStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *GetFleetStatsResponse) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *GetFleetStatsResponse) GetReserve() int32 {
	if x != nil {
		return x.Reserve
	}
	return 0
}

func (x *GetFleetStatsResponse) GetTraining() int32 {
	if x != nil {
		return x.Training
	}
	return 0
}

func (x *GetFleetStatsResponse) GetAverageAge() float32 {
	if x != nil {
		return x.AverageAge
	}
	return 0
}

type VehicleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicle *Vehicle `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Created bool     `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *VehicleResponse) Reset() {
	*x = VehicleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleResponse) ProtoMessage() {}

func (x *VehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleResponse.ProtoReflect.Descriptor instead.
func (*VehicleResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *VehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *VehicleResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type VehicleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicles []*Vehicle `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
}

func (x *VehicleList) Reset() {
	*x = VehicleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleList) ProtoMessage() {}

func (x *VehicleList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_fleet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleList.ProtoReflect.Descriptor instead.
func (*VehicleList) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *VehicleList) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

var File_internal_protobuf_schema_fleet_proto protoreflect.FileDescriptor

var file_internal_protobuf_schema_fleet_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x02, 0x0a, 0x07, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x12, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x66, 0x62, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x66, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61,
	0x6b, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x66, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6c, 0x69, 0x66, 0x65, 0x22, 0xec, 0x01, 0x0a, 0x0e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x66, 0x62, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x66, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x66, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x6c, 0x69, 0x66, 0x65, 0x22, 0x36, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x42, 0x79, 0x4f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2e, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x59, 0x65, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x5a, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6d,
	0x61, 0x6b, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x6d, 0x61, 0x6b, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x46, 0x6c, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x67,
	0x65, 0x22, 0x55, 0x0a, 0x0f, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x56, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x39, 0x0a, 0x0b, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x76, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x32, 0xf9, 0x02, 0x0a, 0x0c, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x15, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e,
	0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x52, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x42, 0x79, 0x4f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x2e, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x42, 0x79,
	0x4f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x59, 0x65, 0x61, 0x72, 0x12, 0x1f, 0x2e, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x42, 0x79,
	0x59, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x1b, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x65, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x65, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protobuf_schema_fleet_proto_rawDescOnce sync.Once
	file_internal_protobuf_schema_fleet_proto_rawDescData = file_internal_protobuf_schema_fleet_proto_rawDesc
)

func file_internal_protobuf_schema_fleet_proto_rawDescGZIP() []byte {
	file_internal_protobuf_schema_fleet_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_schema_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protobuf_schema_fleet_proto_rawDescData)
	})
	return file_internal_protobuf_schema_fleet_proto_rawDescData
}

var file_internal_protobuf_schema_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_protobuf_schema_fleet_proto_goTypes = []interface{}{
	(*Vehicle)(nil),                      // 0: fleet.Vehicle
	(*VehicleRequest)(nil),               // 1: fleet.VehicleRequest
	(*GetVehiclesByOpStatusRequest)(nil), // 2: fleet.GetVehiclesByOpStatusRequest
	(*GetVehiclesByYearRequest)(nil),     // 3: fleet.GetVehiclesByYearRequest
	(*GetFleetStatsRequest)(nil),         // 4: fleet.GetFleetStatsRequest
	(*GetFleetStatsResponse)(nil),        // 5: fleet.GetFleetStatsResponse
	(*VehicleResponse)(nil),              // 6: fleet.VehicleResponse
	(*VehicleList)(nil),                  // 7: fleet.VehicleList
	(*emptypb.Empty)(nil),                // 8: google.protobuf.Empty
}
var file_internal_protobuf_schema_fleet_proto_depIdxs = []int32{
	0, // 0: fleet.VehicleResponse.vehicle:type_name -> fleet.Vehicle
	0, // 1: fleet.VehicleList.vehicles:type_name -> fleet.Vehicle
	8, // 2: fleet.FleetService.ListVehicles:input_type -> google.protobuf.Empty
	1, // 3: fleet.FleetService.AddVehicle:input_type -> fleet.VehicleRequest
	2, // 4: fleet.FleetService.GetVehiclesByOpStatus:input_type -> fleet.GetVehiclesByOpStatusRequest
	3, // 5: fleet.FleetService.GetVehiclesByYear:input_type -> fleet.GetVehiclesByYearRequest
	4, // 6: fleet.FleetService.GetFleetStats:input_type -> fleet.GetFleetStatsRequest
	7, // 7: fleet.FleetService.ListVehicles:output_type -> fleet.VehicleList
	6, // 8: fleet.FleetService.AddVehicle:output_type -> fleet.VehicleResponse
	7, // 9: fleet.FleetService.GetVehiclesByOpStatus:output_type -> fleet.VehicleList
	7, // 10: fleet.FleetService.GetVehiclesByYear:output_type -> fleet.VehicleList
	5, // 11: fleet.FleetService.GetFleetStats:output_type -> fleet.GetFleetStatsResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_protobuf_schema_fleet_proto_init() }
func file_internal_protobuf_schema_fleet_proto_init() {
	if File_internal_protobuf_schema_fleet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protobuf_schema_fleet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vehicle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_fleet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_fleet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVehiclesByOpStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_fleet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVehiclesByYearRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_fleet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFleetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_fleet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFleetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_fleet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_fleet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_protobuf_schema_fleet_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protobuf_schema_fleet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_schema_fleet_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_schema_fleet_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_schema_fleet_proto_msgTypes,
	}.Build()
	File_internal_protobuf_schema_fleet_proto = out.File
	file_internal_protobuf_schema_fleet_proto_rawDesc = nil
	file_internal_protobuf_schema_fleet_proto_goTypes = nil
	file_internal_protobuf_schema_fleet_proto_depIdxs = nil
}
