// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/protobuf/schema/incident.proto

package incident

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Incident struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number               int64                    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	CallDatetime         *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=call_datetime,json=callDatetime,proto3" json:"call_datetime,omitempty"`
	Year                 int32                    `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Type                 string                   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	PumpCount            int32                    `protobuf:"varint,5,opt,name=pump_count,json=pumpCount,proto3" json:"pump_count,omitempty"`
	PumpHoursTotal       int32                    `protobuf:"varint,6,opt,name=pump_hours_total,json=pumpHoursTotal,proto3" json:"pump_hours_total,omitempty"`
	IncidentHourlyCost   int32                    `protobuf:"varint,7,opt,name=incident_hourly_cost,json=incidentHourlyCost,proto3" json:"incident_hourly_cost,omitempty"`
	IncidentNotionalCost int32                    `protobuf:"varint,8,opt,name=incident_notional_cost,json=incidentNotionalCost,proto3" json:"incident_notional_cost,omitempty"`
	AnimalGroup          string                   `protobuf:"bytes,10,opt,name=animal_group,json=animalGroup,proto3" json:"animal_group,omitempty"`
	FinalDescription     string                   `protobuf:"bytes,11,opt,name=final_description,json=finalDescription,proto3" json:"final_description,omitempty"`
	Origin               *Incident_Call           `protobuf:"bytes,12,opt,name=origin,proto3" json:"origin,omitempty"`
	Property             *Incident_Property       `protobuf:"bytes,13,opt,name=property,proto3" json:"property,omitempty"`
	SpecialService       *Incident_SpecialService `protobuf:"bytes,14,opt,name=special_service,json=specialService,proto3" json:"special_service,omitempty"`
	Ward                 *Incident_Ward           `protobuf:"bytes,15,opt,name=ward,proto3" json:"ward,omitempty"`
	Address              *Incident_Address        `protobuf:"bytes,16,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Incident) Reset() {
	*x = Incident{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{0}
}

func (x *Incident) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Incident) GetCallDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.CallDatetime
	}
	return nil
}

func (x *Incident) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Incident) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Incident) GetPumpCount() int32 {
	if x != nil {
		return x.PumpCount
	}
	return 0
}

func (x *Incident) GetPumpHoursTotal() int32 {
	if x != nil {
		return x.PumpHoursTotal
	}
	return 0
}

func (x *Incident) GetIncidentHourlyCost() int32 {
	if x != nil {
		return x.IncidentHourlyCost
	}
	return 0
}

func (x *Incident) GetIncidentNotionalCost() int32 {
	if x != nil {
		return x.IncidentNotionalCost
	}
	return 0
}

func (x *Incident) GetAnimalGroup() string {
	if x != nil {
		return x.AnimalGroup
	}
	return ""
}

func (x *Incident) GetFinalDescription() string {
	if x != nil {
		return x.FinalDescription
	}
	return ""
}

func (x *Incident) GetOrigin() *Incident_Call {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Incident) GetProperty() *Incident_Property {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *Incident) GetSpecialService() *Incident_SpecialService {
	if x != nil {
		return x.SpecialService
	}
	return nil
}

func (x *Incident) GetWard() *Incident_Ward {
	if x != nil {
		return x.Ward
	}
	return nil
}

func (x *Incident) GetAddress() *Incident_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type IncidentList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Incidents []*Incident `protobuf:"bytes,1,rep,name=incidents,proto3" json:"incidents,omitempty"`
}

func (x *IncidentList) Reset() {
	*x = IncidentList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncidentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentList) ProtoMessage() {}

func (x *IncidentList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentList.ProtoReflect.Descriptor instead.
func (*IncidentList) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{1}
}

func (x *IncidentList) GetIncidents() []*Incident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

type GetIncidentsByAnimalGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *GetIncidentsByAnimalGroupRequest) Reset() {
	*x = GetIncidentsByAnimalGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncidentsByAnimalGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentsByAnimalGroupRequest) ProtoMessage() {}

func (x *GetIncidentsByAnimalGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentsByAnimalGroupRequest.ProtoReflect.Descriptor instead.
func (*GetIncidentsByAnimalGroupRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{2}
}

func (x *GetIncidentsByAnimalGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type Incident_Call struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *Incident_Call) Reset() {
	*x = Incident_Call{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident_Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident_Call) ProtoMessage() {}

func (x *Incident_Call) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident_Call.ProtoReflect.Descriptor instead.
func (*Incident_Call) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Incident_Call) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type Incident_Property struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *Incident_Property) Reset() {
	*x = Incident_Property{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident_Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident_Property) ProtoMessage() {}

func (x *Incident_Property) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident_Property.ProtoReflect.Descriptor instead.
func (*Incident_Property) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Incident_Property) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Incident_Property) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type Incident_SpecialService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *Incident_SpecialService) Reset() {
	*x = Incident_SpecialService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident_SpecialService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident_SpecialService) ProtoMessage() {}

func (x *Incident_SpecialService) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident_SpecialService.ProtoReflect.Descriptor instead.
func (*Incident_SpecialService) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Incident_SpecialService) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Incident_SpecialService) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type Incident_Ward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Incident_Ward) Reset() {
	*x = Incident_Ward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident_Ward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident_Ward) ProtoMessage() {}

func (x *Incident_Ward) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident_Ward.ProtoReflect.Descriptor instead.
func (*Incident_Ward) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Incident_Ward) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Incident_Ward) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Incident_Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoroughInfo      *Incident_Address_Borough `protobuf:"bytes,1,opt,name=borough_info,json=boroughInfo,proto3" json:"borough_info,omitempty"`
	Street           string                    `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	Usrn             string                    `protobuf:"bytes,3,opt,name=usrn,proto3" json:"usrn,omitempty"`
	PostcodeDistrict string                    `protobuf:"bytes,4,opt,name=postcode_district,json=postcodeDistrict,proto3" json:"postcode_district,omitempty"`
	Latitude         float64                   `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                   `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Incident_Address) Reset() {
	*x = Incident_Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident_Address) ProtoMessage() {}

func (x *Incident_Address) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident_Address.ProtoReflect.Descriptor instead.
func (*Incident_Address) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Incident_Address) GetBoroughInfo() *Incident_Address_Borough {
	if x != nil {
		return x.BoroughInfo
	}
	return nil
}

func (x *Incident_Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Incident_Address) GetUsrn() string {
	if x != nil {
		return x.Usrn
	}
	return ""
}

func (x *Incident_Address) GetPostcodeDistrict() string {
	if x != nil {
		return x.PostcodeDistrict
	}
	return ""
}

func (x *Incident_Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Incident_Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Incident_Address_Borough struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StnGroundName string `protobuf:"bytes,3,opt,name=stn_ground_name,json=stnGroundName,proto3" json:"stn_ground_name,omitempty"`
}

func (x *Incident_Address_Borough) Reset() {
	*x = Incident_Address_Borough{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protobuf_schema_incident_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident_Address_Borough) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident_Address_Borough) ProtoMessage() {}

func (x *Incident_Address_Borough) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_schema_incident_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident_Address_Borough.ProtoReflect.Descriptor instead.
func (*Incident_Address_Borough) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_schema_incident_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *Incident_Address_Borough) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Incident_Address_Borough) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Incident_Address_Borough) GetStnGroundName() string {
	if x != nil {
		return x.StnGroundName
	}
	return ""
}

var File_internal_protobuf_schema_incident_proto protoreflect.FileDescriptor

var file_internal_protobuf_schema_incident_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x69, 0x6e, 0x63, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x6e, 0x63, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb4, 0x09, 0x0a, 0x08, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x6d, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x75, 0x6d, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28,
	0x0a, 0x10, 0x70, 0x75, 0x6d, 0x70, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x5f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x70, 0x75, 0x6d, 0x70, 0x48, 0x6f,
	0x75, 0x72, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x14, 0x69, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x6c, 0x79, 0x5f, 0x63, 0x6f, 0x73, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x48, 0x6f, 0x75, 0x72, 0x6c, 0x79, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x16, 0x69, 0x6e,
	0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f,
	0x63, 0x6f, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x69, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x2b, 0x0a, 0x11, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x49,
	0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x4a, 0x0a, 0x0f, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x49,
	0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x77, 0x61, 0x72, 0x64, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x57, 0x61, 0x72, 0x64, 0x52, 0x04, 0x77,
	0x61, 0x72, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x1e, 0x0a, 0x04, 0x43, 0x61, 0x6c,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x1a, 0x3a, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x1a, 0x40, 0x0a, 0x0e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x1a, 0x2e, 0x0a, 0x04, 0x57, 0x61, 0x72, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0xbe, 0x02, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x45, 0x0a, 0x0c, 0x62, 0x6f, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x69, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x52, 0x0b, 0x62,
	0x6f, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x72, 0x6e, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x6f, 0x73, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x70, 0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x1a, 0x59, 0x0a,
	0x07, 0x42, 0x6f, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0f, 0x73, 0x74, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x6e, 0x47, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x49, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e,
	0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x52,
	0x09, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x20, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x32, 0xb7, 0x01, 0x0a, 0x0f, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x16, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6e, 0x63,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x2a, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x42, 0x79, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x17,
	0x5a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69,
	0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protobuf_schema_incident_proto_rawDescOnce sync.Once
	file_internal_protobuf_schema_incident_proto_rawDescData = file_internal_protobuf_schema_incident_proto_rawDesc
)

func file_internal_protobuf_schema_incident_proto_rawDescGZIP() []byte {
	file_internal_protobuf_schema_incident_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_schema_incident_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protobuf_schema_incident_proto_rawDescData)
	})
	return file_internal_protobuf_schema_incident_proto_rawDescData
}

var file_internal_protobuf_schema_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_protobuf_schema_incident_proto_goTypes = []interface{}{
	(*Incident)(nil),                         // 0: incident.Incident
	(*IncidentList)(nil),                     // 1: incident.IncidentList
	(*GetIncidentsByAnimalGroupRequest)(nil), // 2: incident.GetIncidentsByAnimalGroupRequest
	(*Incident_Call)(nil),                    // 3: incident.Incident.Call
	(*Incident_Property)(nil),                // 4: incident.Incident.Property
	(*Incident_SpecialService)(nil),          // 5: incident.Incident.SpecialService
	(*Incident_Ward)(nil),                    // 6: incident.Incident.Ward
	(*Incident_Address)(nil),                 // 7: incident.Incident.Address
	(*Incident_Address_Borough)(nil),         // 8: incident.Incident.Address.Borough
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 10: google.protobuf.Empty
}
var file_internal_protobuf_schema_incident_proto_depIdxs = []int32{
	9,  // 0: incident.Incident.call_datetime:type_name -> google.protobuf.Timestamp
	3,  // 1: incident.Incident.origin:type_name -> incident.Incident.Call
	4,  // 2: incident.Incident.property:type_name -> incident.Incident.Property
	5,  // 3: incident.Incident.special_service:type_name -> incident.Incident.SpecialService
	6,  // 4: incident.Incident.ward:type_name -> incident.Incident.Ward
	7,  // 5: incident.Incident.address:type_name -> incident.Incident.Address
	0,  // 6: incident.IncidentList.incidents:type_name -> incident.Incident
	8,  // 7: incident.Incident.Address.borough_info:type_name -> incident.Incident.Address.Borough
	10, // 8: incident.IncidentService.ListIncidents:input_type -> google.protobuf.Empty
	2,  // 9: incident.IncidentService.GetIncidentsByAnimalGroup:input_type -> incident.GetIncidentsByAnimalGroupRequest
	1,  // 10: incident.IncidentService.ListIncidents:output_type -> incident.IncidentList
	1,  // 11: incident.IncidentService.GetIncidentsByAnimalGroup:output_type -> incident.IncidentList
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_protobuf_schema_incident_proto_init() }
func file_internal_protobuf_schema_incident_proto_init() {
	if File_internal_protobuf_schema_incident_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protobuf_schema_incident_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Incident); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_incident_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncidentList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_incident_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIncidentsByAnimalGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_incident_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Incident_Call); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_incident_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Incident_Property); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_incident_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Incident_SpecialService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_incident_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Incident_Ward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_incident_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Incident_Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protobuf_schema_incident_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Incident_Address_Borough); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protobuf_schema_incident_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_schema_incident_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_schema_incident_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_schema_incident_proto_msgTypes,
	}.Build()
	File_internal_protobuf_schema_incident_proto = out.File
	file_internal_protobuf_schema_incident_proto_rawDesc = nil
	file_internal_protobuf_schema_incident_proto_goTypes = nil
	file_internal_protobuf_schema_incident_proto_depIdxs = nil
}
